# Generated by Django 4.0 on 2023-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_station_delete_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='station',
            name='altitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='ebikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='has_ebikes',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='normal_bikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='post_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='renting',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='returning',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='slots',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
