# Generated by Django 4.0 on 2023-02-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_station_address_station_altitude_station_ebikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='last_updated',
            field=models.IntegerField(null=True),
        ),
    ]
