# Generated by Django 4.0 on 2023-02-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_alter_station_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='post_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
