# Generated by Django 4.0 on 2023-02-16 15:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0006_alter_station_address_alter_station_altitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='payment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('key', 'Tarjeta'), ('transitcard', 'Tarjeta de Transito'), ('creditcard', 'Tarjeta de Crédito'), ('phone', 'Teléfono Movil')], max_length=32, null=True),
        ),
    ]
