# Generated by Django 4.0 on 2023-02-17 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0007_station_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='free_bikes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Free Bikes'),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
