# Generated by Django 4.0 on 2023-02-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('tipologia', models.CharField(max_length=255)),
                ('titular', models.CharField(max_length=255)),
                ('inversion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
