# Generated by Django 4.0 on 2023-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyects',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
