# Generated by Django 4.0 on 2023-02-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seia', '0002_proyects_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyects',
            name='fecha',
            field=models.CharField(max_length=255),
        ),
    ]
